name: Deploy Static HTML/JS

on:
  push:
    branches:
      - 'master' # ou 'master', vérifiez le nom de votre branche principale
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js 📦
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify Secrets Presence 🕵️
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          if [ -z "$SUPABASE_URL" ]; then echo "::error::SUPABASE_URL secret is missing!"; exit 1; fi
          if [ -z "$SUPABASE_KEY" ]; then echo "::error::SUPABASE_KEY secret is missing!"; exit 1; fi
          echo "Secrets are correctly loaded in the environment."

      - name: Build Project 🛠️
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node build.js
          # Suppression radicale du .gitignore pour garantir que TOUS les fichiers de 'public' (dont config.js) soient déployés
          rm -f .gitignore

      - name: Verify Build Output 🧐
        run: |
          echo "Checking if public/config.js was created..."
          if [ -f public/config.js ]; then
            echo "✅ File exists. Content (secrets masked):"
            cat public/config.js
          else
            echo "::error::❌ public/config.js is missing!"
            exit 1
          fi

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # Deploy the 'public' folder generated by build.js